language: swift
xcode_workspace: u4ea.xcworkspace
xcode_scheme: u4ea
osx_image: xcode9
xcode_sdk: iphonesimulator11
install: true
cache: cocoapods
before_install:
- bundle install
- export IOS_SIMULATOR_UDID=`instruments -s devices | grep "iPhone 7 (11.0" | awk -F '[ ]' '{print $4}' | awk -F '[\[]' '{print $2}' | sed 's/.$//'`
- echo $IOS_SIMULATOR_UDID
- open -a "simulator" --args -CurrentDeviceUDID $IOS_SIMULATOR_UDID
before_script:
- pod repo update
- pod install
- chmod u+x ./scripts/acceptance-tests.sh
- bundle exec danger
script:
- travis_retry ./scripts/acceptance-tests.sh
