platform :ios, '10.0'
use_frameworks!

target 'u4ea' do
  pod 'Alamofire', '~> 4.2.0'
  pod 'MBProgressHUD', '~> 1.0.0'
  pod 'SwiftyJSON', '~> 3.1.3'
  pod 'IQKeyboardManagerSwift', '~> 4.0.8'
  pod 'SDWebImage', '~> 3.8'
  pod 'BAFluidView', :git => 'https://github.com/aguscha333/BAFluidView.git', :branch => 'change_wave_speed'
  pod 'MBSegueCollection'
  pod 'Flurry-iOS-SDK/FlurrySDK'
  pod 'TwitterKit', '~> 3.1.1'
  pod 'Branch', '~> 0.17.6'
  
  # FB SDK ---
  pod 'FBSDKCoreKit', '~> 4.27.0'
  pod 'FBSDKLoginKit', '~> 4.27.0'
  pod 'FBSDKShareKit', '~> 4.27.0'
end

target 'AcceptanceTests' do
  pod 'KIF', '~> 3.5.2', :configurations => ['Debug']
  pod 'KIF/IdentifierTests', '~> 3.5.2', :configurations => ['Debug']
  pod 'OHHTTPStubs/Swift', '~> 6.0.0', :configurations => ['Debug']
end
